#!/usr/bin/env bash
# 
# Used to generate all the *.toml files from the programs.
#
set -euo pipefail

cd "$(dirname "$0")"

# Get the system tuple for later
system=$(nix eval --raw --impure --expr 'builtins.currentSystem')

# To make sorting reproducible
export LC_ALL=C

# Clean previous version
rm ./*.toml || true
trap 'rm result' EXIT

# Generate for each example
for file in ../programs/*.nix; do
  if [[ $file = *default.nix ]]; then continue; fi
  name=$(echo "$file" | cut -d / -f 3 | cut -d '.' -f 1)
  echo "# $name.toml"

  nix build ".#checks.$system.$name"

  {
    echo "# Example generated by ./generate.sh"
    sed -n '/^$/q;p' ./result | sed 's|\(command = "\).*/\([^"]\+"\)|\1\2|'
  } > "$name.toml"
done
